name: PastorP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5
title: The Deep End of Discipleship
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#28aa93'
    - '#187766'
    - '#6fb6a9'
    - '#a8cdc6'
  brandStrength: 0.625
  lightness: 0.8937184207607061
  saturation: 0.7828230797313154
  rhythmicContrast: 0.5
purpose: []
